spring:
  application:
    name: hcb-eureka

server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0